### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by robert-m** [appleboy/CodeGPT#44]
Love this tool so much but for some reason I can't get gpt-4 model to work at all. gpt-3.5-turbo works just fine. Any help would be greatly appreciated.

```console
codegpt version
version: 0.1.3 commit: 51a0f34

codegpt commit
Summarize the commit message use gpt-4 model
We are trying to summarize a git diff
Error: error, status code: 404, message: The model: `gpt-4` does not exist
```

```yml
git:
    diff_unified: 3
    exclude_list: []
    template_file: ""
    template_string: ""
openai:
    api_key: sk-########
    base_url: ""
    model: gpt-4
    org_id: org-#######
    proxy: ""
    socks: ""
    timeout: 15s
output:
    file: .git/COMMIT_EDITMSG
    lang: en

```
