### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by wl02599509** [appleboy/CodeGPT#61]
This is my codegpt.yaml:
```
openai:
    api_key: sk-foobar123examplekey
    base_url: ""
    model: 'gpt-4'
    org_id: ""
    proxy: ""
    socks: ""
    timeout: 30s
```

The error message 'Error: error, status code: 404, message: The model: `gpt-4` does not exist' pop up after I input `codegpt commit --preview`.
Is there any errors on my config?
( I'm using CHATGPT-4 )
